name: 'Upgrade Go Action'
description: 'Checks if there is an Go upgrade and create an pull requests if so'
inputs:
  base-branch:
    description: 'The (base) branch where the PR will be created at. Default is main'
    required: false
    default: 'main'
runs:
  using: 'node16'
  main: 'dist/index.js'
