name: 'Upgrade Go Action'
description: 'Check if there is a Go upgrade available, and create a pull request if there is.'
inputs:
  base-branch:
    description: 'The (base) branch where the PR will be created at. Default is main'
    required: false
    default: 'main'
runs:
  using: 'node20'
  main: 'dist/index.js'
