name: 'Upgrade Go Action'
description: 'Check if there is a Go upgrade available, and create a pull request if there is.'
inputs:
  base-branch:
    description: 'The (base) branch where the PR will be created at. Default is main'
    required: false
    default: 'main'
  gh-token:
    description: 'The GitHub token'
    required: false
    default: ${{ github.token }}
  dry-run:
    description: 'If true, the action will only check for upgrades and not create a PR. Default is false'
    required: false
    default: 'false'
runs:
  using: 'node24'
  main: 'dist/index.js'
