name: 'Test Action'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testAction:
    strategy:
      matrix:
        # Right now macos-13 is amd64 while macos-14 is aarch64 (M1)
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test go.mod file
        run: |
          echo "module github.com/Upgrade-Go-Action" >> go.mod
          echo "go 1.17" >> go.mod
          cat go.mod

      - name: Test Local Action
        uses: ./
        with:
          dry-run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check go.mod file
        run: cat go.mod